server:
  port: 8080

spring:
  application:
    name: supplier-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/supplier_db1

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
